variables:
  IMAGE_REPO: dockerhub.qingcloud.com/lowcode

stages:
  - install
  - test
  - build
  - release

cache:
  key: node_modules
  paths:
    - node_modules/

install_node_modules_go_packages:
  tags:
    - qxp-web-runner
  stage: install
  script:
    - yarn install --registry=http://r.npm.internal.yunify.com

lint_js:
  tags:
    - qxp-web-runner
  stage: test
  script:
    - yarn run lint

integrate:
  tags:
    - qxp-web-runner
  stage: test
  script:
    - node_modules/.bin/tsc --noEmit --skipLibCheck --pretty

build_all:
  tags:
    - qxp-web-runner
  stage: build
  only:
    - tags
    - release
  script:
    - node_modules/.bin/gulp buildAssets
    - NODE_ENV=production ./node_modules/.bin/rollup --config rollup.config.js
    - go mod tidy
    - go mod vendor
    - IMAGE_TAG="v$(date "+%Y%m%d")-$(git rev-parse --short HEAD)"
    - docker build -t "$IMAGE_REPO/qxp-web-portal:$IMAGE_TAG" -f ./deploy/Dockerfile-portal .
    - docker build -t "$IMAGE_REPO/qxp-web-home:$IMAGE_TAG" -f ./deploy/Dockerfile-home .
    - docker build -t "$IMAGE_REPO/qxp-web-nginx:$IMAGE_TAG" -f ./deploy/Dockerfile-nginx .
    - docker push "$IMAGE_REPO/qxp-web-nginx:$IMAGE_TAG"
    - docker push "$IMAGE_REPO/qxp-web-portal:$IMAGE_TAG"
    - docker push "$IMAGE_REPO/qxp-web-home:$IMAGE_TAG"
    - docker rmi "$IMAGE_REPO/qxp-web-nginx:$IMAGE_TAG"
    - docker rmi "$IMAGE_REPO/qxp-web-portal:$IMAGE_TAG"
    - docker rmi "$IMAGE_REPO/qxp-web-home:$IMAGE_TAG"

deploy_alpha:
  tags:
    - qxp-web-runner
  stage: release
  only:
    - alpha
  script:
    - ./scripts/deploy_alpha.sh

deploy_testing:
  tags:
    - qxp-web-runner
  stage: release
  only:
    - release
  script:
    - IMAGE_TAG="v$(date "+%Y%m%d")-$(git rev-parse --short HEAD)"
    - bash -c "helm upgrade quanxiang /root/quanxiang_charts --set qxp-web-portal.image.tag=$IMAGE_TAG --set qxp-web-portal.image.repo=$IMAGE_REPO -n lowcode"
    - bash -c "helm upgrade quanxiang /root/quanxiang_charts --set qxp-web-home.image.tag=$IMAGE_TAG --set qxp-web-home.image.repo=$IMAGE_REPO -n lowcode"
    - bash -c "helm upgrade quanxiang /root/quanxiang_charts --set qxp-web-nginx.image.tag=$IMAGE_TAG --set qxp-web-nginx.image.repo=$IMAGE_REPO -n lowcode"
    - echo "deploy testing done!"

deploy_staging:
  tags:
    - qxp-web-runner
  stage: release
  only:
    - tags
    - /^v(\d+\.)+(\d+)/
  except:
    - branches
  script:
    - IMAGE_TAG="v$(date "+%Y%m%d")-$(git rev-parse --short HEAD)"
    - bash -c "helm upgrade quanxiang /root/quanxiang_charts --set qxp-web-portal.image.tag=$IMAGE_TAG --set qxp-web-portal.image.repo=$IMAGE_REPO -n lowcode --kubeconfig ~/.kube/config_staging"
    - bash -c "helm upgrade quanxiang /root/quanxiang_charts --set qxp-web-home.image.tag=$IMAGE_TAG --set qxp-web-home.image.repo=$IMAGE_REPO -n lowcode --kubeconfig ~/.kube/config_staging"
    - bash -c "helm upgrade quanxiang /root/quanxiang_charts --set qxp-web-nginx.image.tag=$IMAGE_TAG --set qxp-web-nginx.image.repo=$IMAGE_REPO -n lowcode --kubeconfig ~/.kube/config_staging"
    - echo "deploy staging done!"
