variables:
  IMAGE_PREFIX: dockerhub.qingcloud.com/qxpdev

stages:
  - install
  - test
  - build
  - release

cache:
  key: node_modules
  paths:
    - node_modules/

install_node_modules_go_packages:
  tags:
    - qxp-web-runner
  stage: install
  script:
    - yarn install --registry=http://r.npm.internal.yunify.com

lint_js:
  tags:
    - qxp-web-runner
  stage: test
  script:
    - yarn run lint

integrate:
  tags:
    - qxp-web-runner
  stage: test
  script:
    - yarn run lint
    - NODE_ENV=production ./node_modules/.bin/webpack --config webpack.config.js

build_all:
  tags:
    - qxp-web-runner
  stage: build
  only:
    - /release\/.*/
  script:
    - node_modules/.bin/gulp buildAssets
    - NODE_ENV=production ./node_modules/.bin/webpack --config webpack.config.js
    - go mod tidy
    - go mod vendor
    - IMAGE_TAG="v$(date "+%Y%m%d")-$(git rev-parse --short HEAD)"
    - docker build -t "$IMAGE_PREFIX/qxp-web-portal:$IMAGE_TAG" -f ./deploy/Dockerfile-portal .
    - docker build -t "$IMAGE_PREFIX/qxp-web-home:$IMAGE_TAG" -f ./deploy/Dockerfile-home .
    - docker build -t "$IMAGE_PREFIX/qxp-web-nginx:$IMAGE_TAG" -f ./deploy/Dockerfile-nginx .
    - docker push "$IMAGE_PREFIX/qxp-web-nginx:$IMAGE_TAG"
    - docker push "$IMAGE_PREFIX/qxp-web-portal:$IMAGE_TAG"
    - docker push "$IMAGE_PREFIX/qxp-web-home:$IMAGE_TAG"

deploy_alpha:
  tags:
    - qxp-web-runner
  stage: build
  only:
    - alpha
  script:
    - ./scripts/deploy_alpha.sh

deploy_testing:
  tags:
    - qxp-web-runner
  stage: release
  only:
    - /release\/.*/
  script:
    - IMAGE_TAG="v$(date "+%Y%m%d")-$(git rev-parse --short HEAD)"
    - bash -c "helm upgrade qxp-web-portal /root/deployment/qxp-web-portal --set image.tag=$IMAGE_TAG"
    - bash -c "helm upgrade qxp-web-home /root/deployment/qxp-web-home --set image.tag=$IMAGE_TAG"
    - bash -c "helm upgrade qxp-web-nginx /root/deployment/qxp-web-nginx --set image.tag=$IMAGE_TAG"
    - echo "deploy testing done!"
