name: client-boot
description: checkout code, install dependencies
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        path: ./node_modules
    - run: yarn install
      shell: bash
