name: Build for testing environment
env:
  IMAGE_REPO: dockerhub.qingcloud.com/lowcode
  DATE: $(date "+%Y%m%d")
on:
  push:
    branches:
      - 'release/**'
      - release/v1.0.0
jobs:
  bundle-clients:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/client-boot-up
      - uses: ./.github/actions/quality-check
      - uses: ./.github/actions/build-static
  build-qxp-web-nginx:
    needs: [bundle-clients]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Download client statices
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - run: echo IMAGE_TAG="v${{ env.DATE }}-${GITHUB_SHA::7}" >> $GITHUB_ENV
      - run: docker build -t "$IMAGE_REPO/qxp-web-nginx:$IMAGE_TAG" -f ./deploy/Dockerfile-nginx .
      - run: docker push "$IMAGE_REPO/qxp-web-nginx:$IMAGE_TAG"
      - run: docker rmi "$IMAGE_REPO/qxp-web-nginx:$IMAGE_TAG"
  build-qxp-web-portal-and-home:
    needs: [bundle-clients]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Download templates and manifest.json
        uses: actions/download-artifact@v3
        with:
          name: templates
          path: dist
      - run: go mod tidy
      - run: go mod vendor
      - run: echo IMAGE_TAG="v${{ env.DATE }}-${GITHUB_SHA::7}" >> $GITHUB_ENV
      - run: docker build -t "$IMAGE_REPO/qxp-web-portal:$IMAGE_TAG" -f ./deploy/Dockerfile-portal .
      - run: docker build -t "$IMAGE_REPO/qxp-web-home:$IMAGE_TAG" -f ./deploy/Dockerfile-home .
      - run: docker push "$IMAGE_REPO/qxp-web-portal:$IMAGE_TAG"
      - run: docker push "$IMAGE_REPO/qxp-web-home:$IMAGE_TAG"
      - run: docker rmi "$IMAGE_REPO/qxp-web-portal:$IMAGE_TAG"
      - run: docker rmi "$IMAGE_REPO/qxp-web-home:$IMAGE_TAG"
  deploy-testing:
    needs: [build-qxp-web-nginx, build-qxp-web-portal-and-home]
    runs-on: self-hosted
    steps:
      - run: echo IMAGE_TAG="v${{ env.DATE }}-${GITHUB_SHA::7}" >> $GITHUB_ENV
      - run: bash -c "/opt/upImage.sh $IMAGE_REPO/qxp-web-nginx:$IMAGE_TAG $GITHUB_REF_NAME"
      - run: bash -c "/opt/upImage.sh $IMAGE_REPO/qxp-web-portal:$IMAGE_TAG $GITHUB_REF_NAME"
      - run: bash -c "/opt/upImage.sh $IMAGE_REPO/qxp-web-home:$IMAGE_TAG $GITHUB_REF_NAME"
